// src/app/components/settings-overlay/settings-overlay.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { SettingsService } from '../../services/settings.service';
import { BehaviorSubject } from 'rxjs';
import ISettings from '../../../interfaces/ISettings';
import { TranslateService } from '@ngx-translate/core';
import {GenericService} from "../../services/generic.service";
import {revealItemInDir} from "@tauri-apps/plugin-opener";
import {configDir} from "@tauri-apps/api/path";
import {platform} from "@tauri-apps/plugin-os";
import {invoke} from "@tauri-apps/api/core";
import {FileSelectEvent} from "primeng/fileupload";
import { open } from '@tauri-apps/plugin-dialog';

@Component({
	selector: 'app-settings-overlay',
	templateUrl: './settings-overlay.component.html',
	styleUrl: './settings-overlay.component.css',
})
export class SettingsOverlayComponent implements OnInit {
	@Input()
	visible: boolean = false;
	@Output()
	visibleChange = new EventEmitter<boolean>();
	settings: BehaviorSubject<ISettings> = new BehaviorSubject<ISettings>({});
	themes: any[] = [
		{ label: 'Bootstrap4 Light Blue', value: 'bootstrap4-light-blue.css' },
		{
			label: 'Bootstrap4 Light Purple',
			value: 'bootstrap4-light-purple.css',
		},
		{ label: 'Bootstrap4 Dark Blue', value: 'bootstrap4-dark-blue.css' },
		{
			label: 'Bootstrap4 Dark Purple',
			value: 'bootstrap4-dark-purple.css',
		},
		{ label: 'MD Light Indigo', value: 'md-light-indigo.css' },
		{ label: 'MD Light Deep Purple', value: 'md-light-deeppurple.css' },
		{ label: 'MD Dark Indigo', value: 'md-dark-indigo.css' },
		{ label: 'MD Dark Deep Purple', value: 'md-dark-deeppurple.css' },
		{ label: 'MDC Light Indigo', value: 'mdc-light-indigo.css' },
		{ label: 'MDC Light Deep Purple', value: 'mdc-light-deeppurple.css' },
		{ label: 'MDC Dark Indigo', value: 'mdc-dark-indigo.css' },
		{ label: 'MDC Dark Deep Purple', value: 'mdc-dark-deeppurple.css' },
		{ label: 'Fluent Light', value: 'fluent-light.css' },
		{ label: 'Lara Light Blue', value: 'lara-light-blue.css' },
		{ label: 'Lara Light Indigo', value: 'lara-light-indigo.css' },
		{ label: 'Lara Light Purple', value: 'lara-light-purple.css' },
		{ label: 'Lara Light Teal', value: 'lara-light-teal.css' },
		{ label: 'Lara Dark Blue', value: 'lara-dark-blue.css' },
		{ label: 'Lara Dark Indigo', value: 'lara-dark-indigo.css' },
		{ label: 'Lara Dark Purple', value: 'lara-dark-purple.css' },
		{ label: 'Lara Dark Teal', value: 'lara-dark-teal.css' },
		{ label: 'Soho Light', value: 'soho-light.css' },
		{ label: 'Soho Dark', value: 'soho-dark.css' },
		{ label: 'Viva Light', value: 'viva-light.css' },
		{ label: 'Viva Dark', value: 'viva-dark.css' },
		{ label: 'Mira', value: 'mira.css' },
		{ label: 'Nano', value: 'nano.css' },
		{ label: 'Saga Blue', value: 'saga-blue.css' },
		{ label: 'Saga Green', value: 'saga-green.css' },
		{ label: 'Saga Orange', value: 'saga-orange.css' },
		{ label: 'Saga Purple', value: 'saga-purple.css' },
		{ label: 'Vela Blue', value: 'vela-blue.css' },
		{ label: 'Vela Green', value: 'vela-green.css' },
		{ label: 'Vela Orange', value: 'vela-orange.css' },
		{ label: 'Vela Purple', value: 'vela-purple.css' },
		{ label: 'Arya Blue', value: 'arya-blue.css' },
		{ label: 'Arya Green', value: 'arya-green.css' },
		{ label: 'Arya Orange', value: 'arya-orange.css' },
		{ label: 'Arya Purple', value: 'arya-purple.css' },
		{ label: 'Nova', value: 'nova.css' },
		{ label: 'Nova Alt', value: 'nova-alt.css' },
		{ label: 'Nova Accent', value: 'nova-accent.css' },
		{ label: 'Luna Amber', value: 'luna-amber.css' },
		{ label: 'Luna Blue', value: 'luna-blue.css' },
		{ label: 'Luna Green', value: 'luna-green.css' },
		{ label: 'Luna Pink', value: 'luna-pink.css' },
		{ label: 'Rhea', value: 'rhea.css' },
	];
	languages: any[] = [
		{ label: 'English', value: 'en' },
		{ label: 'Deutsch', value: 'de' },
		{ label: 'Français', value: 'fr' },
		{ label: 'Italiano', value: 'it' },
		{ label: 'Español', value: 'es' },
		{ label: 'Dev', value: 'dev' },
	];
	activeItem: any;
	items = [{
		label: this.translate.instant('general'),
		icon: 'pi pi-info-circle',
		expanded: true,
		items: [
			{
				label: this.translate.instant('themes'),
				icon: 'pi pi-file',
				command: () => {
					this.activeItem = 'Themes';
				},
			},
			{
				label: this.translate.instant('languages'),
				icon: 'pi pi-id-card',
				command: () => {
					this.activeItem = 'Languages';
				},
			},
			{
				label: this.translate.instant('api-settings'),
				icon: 'pi pi-sliders-h',
				command: () => {
					this.activeItem = 'APIKEYS';
				},
			},
			{
				label: this.translate.instant('Launch Video'),
				icon: 'pi pi-video',
				command: () => {
					this.activeItem = 'LAUNCHVID';
				},
			}
		],
	}, {
		label: this.translate.instant('game-importers'),
		icon: 'pi pi-file-import',
		expanded: true,
		items: [
			{
				label: this.translate.instant('csv-importer'),
				icon: 'pi pi-cloud-upload',
				command: () => {
					this.activeItem = this.translate.instant('csv-importer');
				},
			},
			{
				label: 'Epic Games ' + this.translate.instant('importer'),
				icon: 'pi pi-cloud-download',
				command: () => {
					this.activeItem = 'Epic Games ' +
						this.translate.instant('importer');
				},
			},
			{
				label: 'Steam ' + this.translate.instant('importer'),
				icon: 'pi pi-refresh',
				command: () => {
					this.activeItem = 'Steam ' +
						this.translate.instant('importer');
				},
			},
			{
				label: 'GOG ' + this.translate.instant('importer'),
				icon: 'pi pi-refresh',
				command: () => {
					this.activeItem = 'GOG ' +
						this.translate.instant('importer');
				},
			},
		],
	}, {
		label: this.translate.instant('database-exporters'),
		icon: 'pi pi-file-import',
		expanded: true,
		items: [
			{
				label: this.translate.instant('csv-exporter'),
				icon: 'pi pi-cloud-upload',
				command: () => {
					this.activeItem = this.translate.instant('csv-exporter');
				},
			},
			{
				label: this.translate.instant('archive-exporter'),
				icon: 'pi pi-cloud-upload',
				command: () => {
					this.activeItem = this.translate.instant(
						'archive-exporter',
					);
				},
			},
		],
	}, {
		label: this.translate.instant('about'),
		icon: 'pi pi-info-circle',
		command: () => {
			this.activeItem = this.translate.instant('about');
		},
	}];
	selectedTheme: any;
	selectedLanguage: any;
	appVersion: string = '1.0.0';
	apiKeys: any = {};

	constructor(
		private settingsService: SettingsService,
		private translate: TranslateService,
		protected genericService: GenericService,
	) {}

	changeLanguage() {
		this.settingsService.changeLanguage(this.selectedLanguage.value);
	}

	changeTheme() {
		this.settingsService.changeTheme(this.selectedTheme.value);
	}

	hide() {
		this.visibleChange.emit(false);
	}

	searchThemeFromValue(value: string) {
		return this.themes.find((theme) => theme.value === value);
	}

	searchLanguageFromValue(value: string) {
		return this.languages.find((language) => language.value === value);
	}

	ngOnInit(): void {
		this.selectedTheme =
			(document.getElementById('themeLinker') as HTMLLinkElement).href
				.split('/').pop();
		this.selectedTheme = this.searchThemeFromValue(this.selectedTheme);
		this.selectedLanguage = this.searchLanguageFromValue(
			this.translate.currentLang || 'en',
		);
		this.resolveAppVersion().then((version) => {
			this.appVersion = version;
		});
		this.settingsService.getApiKeys().subscribe((apiKeys) => {
			this.apiKeys = apiKeys;
		});
	}

	async resolveAppVersion() {
		return await this.genericService.getAppVersion();
	}

	setEnv(key: unknown, value: any) {
		this.settingsService.setApiKeys({
			...this.apiKeys,
			[key as string]: value,
		});
		this.settingsService.set_env_settings();
	}

	async openProgramFolder() {
		await invoke('open_program_folder');
	}

	async openDataFolder() {
		await invoke('open_data_folder');
	}

	async openLaunchVideo() {
		const file = await open({
			multiple: false,
			directory: false,
		});
		if (file) {
			await invoke('save_launch_video', { file: file });
		}
	}
}

<p-dialog (onHide)="hide()" [(visible)]="visible"
	[style]="{ maxWidth: '90%', width: '90%', height: '90%', maxHeight: '90%' }" draggable="false" header="Settings"
	modal="true" resizable="false">
	<div class="sideBySide">
		<div>
			<p-panelMenu [model]="items" styleClass="w-full md:w-20rem" />
		</div>
		<div style="width: 100%">
			<div id="content">
				<div *ngIf="activeItem === 'Themes'" id="themes">
					<h3>{{ 'themes' | translate }}</h3>
					<p>{{ 'choose-a-theme' | translate }}</p>
					<p-dropdown (onChange)="changeTheme()" [(ngModel)]="selectedTheme" [options]="themes"
						optionLabel="label" placeholder="{{ 'change-theme' | translate }}" />
				</div>
				<div *ngIf="activeItem === 'Languages'" id="languages">
					<h3>{{ 'languages' | translate }}</h3>
					<p>{{ 'choose-a-language' | translate }}</p>
					<p-dropdown (onChange)="changeLanguage()" [(ngModel)]="selectedLanguage" [options]="languages"
						optionLabel="label" placeholder="{{ 'change-language' | translate }}" />
				</div>
				<div *ngIf="activeItem === 'APIKEYS'" id="APIKEYS">
					<h3>{{ 'api-keys' | translate }}</h3>
					<p>{{ 'settings.api-keys' | translate }}</p>
					<div class="spaceX">
						<div *ngFor="let key of apiKeys | keyvalue" class="mb-3">
							<p-floatLabel>
								<input [(ngModel)]="key.value" pInputText (blur)="setEnv(key.key, key.value)"
									[id]="'id-' + key.key" />
								<label [for]="'id-' + key.key">{{
									key.key
									}}</label>
							</p-floatLabel>
						</div>
					</div>
				</div>
                <div *ngIf="activeItem === 'LAUNCHVID'" id="LAUNCHVID">
                    <h3>{{ 'intro-video' | translate }}</h3>
                    <p>{{ 'settings.intro-video' | translate }}</p>
                    <div class="spaceX">
                        <div class="mb-3">
                           <p-button label="{{ 'upload-a-video' | translate }}" (onClick)="openLaunchVideo()"></p-button>
                        </div>
                    </div>
                </div>

				<app-csv-importer *ngIf="activeItem === 'CSV Importer'"></app-csv-importer>
				<app-csv-exporter *ngIf="activeItem === 'CSV Exporter'"></app-csv-exporter>
				<app-archive-exporter *ngIf="activeItem === 'Archive Exporter'"></app-archive-exporter>
				<app-epic-importer *ngIf="activeItem === 'Epic Games Importer'"></app-epic-importer>
				<app-steam-importer *ngIf="activeItem === 'Steam Importer'"></app-steam-importer>
				<app-gog-importer *ngIf="activeItem === 'GOG Importer'"></app-gog-importer>
				<div *ngIf="activeItem === 'About'" id="about">
					<h2>{{ 'about' | translate }} Meteoric</h2>
					<img alt="{{ 'meteoric-logo' | translate }}" height="235" ngSrc="assets/logo.svg"
						style="width: 100px; height: 100px" width="240" />
					<p>{{ 'version-appversion' | translate }} {{ appVersion }}</p>
					<p class="dev-warning" *ngIf="this.genericService.getDevMode()">
						{{ 'dev-warning' | translate }}
					</p>
					<a href="https://github.com/Nytuo/Meteoric">https://github.com/Nytuo/Meteoric</a>
					<a href="https://github.com/Nytuo/Meteoric/wiki">{{ 'documentation' | translate }}</a>
					<p>
						{{ 'reportIssue' | translate }}
						<a href="https://github.com/Nytuo/Meteoric/issues">GitHub</a>
					</p>
					<p>
						{{ 'features-report' | translate }}
						<a href="https://github.com/Nytuo/Meteoric/issues">GitHub</a>
					</p>
					<p-button label="{{ 'open-program-folder' | translate }}"
						(onClick)="openProgramFolder()"></p-button>
					<br>
					<p-button label="{{ 'open-data-folder' | translate }}" (onClick)="openDataFolder()"></p-button>
				</div>
			</div>
		</div>
	</div>
</p-dialog>

// src/components/overlays/SettingsOverlay.tsx
import { useState, useEffect } from "react";
import { useTranslation } from "react-i18next";
import { invoke } from "@tauri-apps/api/core";
import { open } from "@tauri-apps/plugin-dialog";
import {
	Palette, Video, Key, FileText, ShoppingBag, Server,
	FileOutput, Archive, Info, FolderOpen, Upload, Sun, Moon,
} from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Separator } from "@/components/ui/separator";
import { ScrollArea } from "@/components/ui/scroll-area";
import { useSettingsStore } from "@/stores/settingsStore";
import { useAppStore } from "@/stores/appStore";
import { db } from "@/lib/db";
import { CsvImporter } from "@/components/plugins/CsvImporter";
import { SteamImporter } from "@/components/plugins/SteamImporter";
import { EpicImporter } from "@/components/plugins/EpicImporter";
import { GogImporter } from "@/components/plugins/GogImporter";
import logoSvg from "@/assets/logo.svg";

const languages = [
	{ label: "English", value: "en" },
	{ label: "Deutsch", value: "de" },
	{ label: "Français", value: "fr" },
	{ label: "Italiano", value: "it" },
	{ label: "Español", value: "es" },
	{ label: "Dev", value: "dev" },
];

const ACCENTS = [
	{ value: "default", label: "Default", color: "#a1a1aa" },
	{ value: "blue",    label: "Blue",    color: "#3b82f6" },
	{ value: "purple",  label: "Purple",  color: "#a855f7" },
	{ value: "green",   label: "Green",   color: "#22c55e" },
	{ value: "teal",    label: "Teal",    color: "#14b8a6" },
	{ value: "orange",  label: "Orange",  color: "#f97316" },
	{ value: "red",     label: "Red",     color: "#ef4444" },
];

interface SettingsOverlayProps {
	open: boolean;
	onOpenChange: (open: boolean) => void;
}

export function SettingsOverlay({ open: isOpen, onOpenChange }: SettingsOverlayProps) {
	const { t, i18n } = useTranslation();
	const { settings, apiKeys, fetchApiKeys, setApiKey, saveApiKeys, changeLanguage, changeTheme, changeAccent } = useSettingsStore();
	const { getAppVersion } = useAppStore();

	const [activeItem, setActiveItem] = useState("appearance");
	const [selectedLanguage, setSelectedLanguage] = useState(i18n.language || "en");
	const [appVersion, setAppVersion] = useState("1.0.0");
	const [localApiKeys, setLocalApiKeys] = useState<Record<string, string>>({});

	const currentTheme = settings.theme || "dark";
	const currentAccent = settings.accent || "default";

	useEffect(() => {
		if (isOpen) {
			fetchApiKeys();
			getAppVersion().then(setAppVersion);
		}
	}, [isOpen]);

	useEffect(() => {
		if (apiKeys) setLocalApiKeys({ ...apiKeys });
	}, [apiKeys]);

	const handleLanguageChange = (value: string) => {
		setSelectedLanguage(value);
		changeLanguage(value);
	};

	const handleApiKeyChange = (key: string, value: string) => {
		setLocalApiKeys((prev) => ({ ...prev, [key]: value }));
		setApiKey(key, value);
		saveApiKeys();
	};

	const openProgramFolder = () => invoke("open_program_folder");
	const openDataFolder = () => invoke("open_data_folder");
	const openLaunchVideo = async () => {
		const file = await open({ multiple: false, directory: false });
		if (file) await invoke("save_launch_video", { file });
	};

	const navItems = [
		{ key: "appearance", icon: <Palette className="h-4 w-4" />, label: `${t("themes")} & ${t("languages")}` },
		{ key: "media", icon: <Video className="h-4 w-4" />, label: t("intro-video") },
		{ key: "apikeys", icon: <Key className="h-4 w-4" />, label: t("api-settings") },
		"divider",
		{ key: "divider-label", label: t("game-importers"), type: "label" },
		{ key: "import-csv", icon: <FileText className="h-4 w-4" />, label: t("csv-importer"), sub: true },
		{ key: "import-epic", icon: <ShoppingBag className="h-4 w-4" />, label: "Epic Games", sub: true },
		{ key: "import-steam", icon: <Server className="h-4 w-4" />, label: "Steam", sub: true },
		{ key: "import-gog", icon: <Server className="h-4 w-4" />, label: "GOG", sub: true },
		"divider",
		{ key: "divider-label2", label: t("database-exporters"), type: "label" },
		{ key: "export-csv", icon: <FileOutput className="h-4 w-4" />, label: t("csv-exporter"), sub: true },
		{ key: "export-archive", icon: <Archive className="h-4 w-4" />, label: t("archive-exporter"), sub: true },
		"divider",
		{ key: "about", icon: <Info className="h-4 w-4" />, label: t("about") },
	] as Array<string | { key: string; icon?: React.ReactNode; label: string; type?: string; sub?: boolean }>;

	return (
		<Dialog open={isOpen} onOpenChange={onOpenChange}>
			<DialogContent className="max-w-5xl h-[85vh] p-0 gap-0 overflow-hidden">
				<div className="flex h-full overflow-hidden">
					{/* Sidebar */}
					<div className="flex w-56 shrink-0 flex-col border-r border-border bg-card/50">
						<DialogHeader className="shrink-0 p-4 pb-3">
							<DialogTitle className="text-base">{t("settings") || "Settings"}</DialogTitle>
						</DialogHeader>
						<ScrollArea className="min-h-0 flex-1 px-2 pb-2">
							<nav className="space-y-0.5">
								{navItems.map((item, i) => {
									if (item === "divider") return <Separator key={`d-${i}`} className="my-2" />;
									if (typeof item === "object" && item.type === "label") {
										return <p key={item.key} className="px-3 py-1 text-xs text-muted-foreground font-medium">{item.label}</p>;
									}
									if (typeof item === "object" && "key" in item) {
										return (
											<button
												key={item.key}
												onClick={() => setActiveItem(item.key)}
												className={`flex w-full items-center gap-2 rounded-md px-3 py-2 text-xs transition-colors hover:bg-accent ${
													activeItem === item.key ? "bg-accent text-accent-foreground" : ""
												} ${item.sub ? "pl-6" : ""}`}
											>
												{item.icon}
												<span>{item.label}</span>
											</button>
										);
									}
									return null;
								})}
							</nav>
						</ScrollArea>
					</div>

					{/* Content */}
					<ScrollArea className="min-h-0 flex-1">
						<div className="p-6">
							{/* Appearance: Themes & Languages */}
							{activeItem === "appearance" && (
								<div>
									<h2 className="mb-4 flex items-center gap-2 text-xl font-semibold">
										<Palette className="h-5 w-5" /> {t("themes")} &amp; {t("languages")}
									</h2>

									{/* Color mode */}
									<div className="mb-6">
										<Label className="mb-1 block">{t("colorMode") || "Color Mode"}</Label>
										<p className="mb-3 text-xs text-muted-foreground">{t("choose-a-theme") || "Choose between dark and light mode."}</p>
										<div className="flex gap-3">
											<button
												onClick={() => changeTheme("dark")}
												className={`flex items-center gap-2 rounded-lg border px-4 py-3 text-sm transition-colors hover:bg-accent ${
													currentTheme === "dark" ? "border-primary bg-accent" : "border-border"
												}`}
											>
												<Moon className="h-4 w-4" /> {t("dark") || "Dark"}
											</button>
											<button
												onClick={() => changeTheme("light")}
												className={`flex items-center gap-2 rounded-lg border px-4 py-3 text-sm transition-colors hover:bg-accent ${
													currentTheme === "light" ? "border-primary bg-accent" : "border-border"
												}`}
											>
												<Sun className="h-4 w-4" /> {t("light") || "Light"}
											</button>
										</div>
									</div>

									{/* Accent color */}
									<div className="mb-6">
										<Label className="mb-1 block">{t("accentColor") || "Accent Color"}</Label>
										<p className="mb-3 text-xs text-muted-foreground">{t("choose-an-accent") || "Choose an accent color for interactive elements."}</p>
										<div className="flex flex-wrap gap-2">
											{ACCENTS.map((a) => (
												<button
													key={a.value}
													title={a.label}
													onClick={() => changeAccent(a.value)}
													className={`h-9 w-9 rounded-full border-2 transition-all hover:scale-110 ${
														currentAccent === a.value ? "border-foreground scale-110" : "border-transparent"
													}`}
													style={{ backgroundColor: a.color }}
												/>
											))}
										</div>
									</div>

									{/* Language */}
									<div>
										<Label className="mb-1 block">{t("languages")}</Label>
										<p className="mb-2 text-xs text-muted-foreground">{t("choose-a-language")}</p>
										<Select value={selectedLanguage} onValueChange={handleLanguageChange}>
											<SelectTrigger className="max-w-xs">
												<SelectValue />
											</SelectTrigger>
											<SelectContent>
												{languages.map((l) => (
													<SelectItem key={l.value} value={l.value}>{l.label}</SelectItem>
												))}
											</SelectContent>
										</Select>
									</div>
								</div>
							)}

							{/* Intro Video */}
							{activeItem === "media" && (
								<div>
									<h2 className="mb-4 flex items-center gap-2 text-xl font-semibold">
										<Video className="h-5 w-5" /> {t("intro-video")}
									</h2>
									<p className="mb-4 text-sm text-muted-foreground">{t("settings.intro-video")}</p>
									<Button onClick={openLaunchVideo}>
										<Upload className="mr-2 h-4 w-4" /> {t("upload-a-video")}
									</Button>
								</div>
							)}

							{/* API Keys */}
							{activeItem === "apikeys" && (
								<div>
									<h2 className="mb-4 flex items-center gap-2 text-xl font-semibold">
										<Key className="h-5 w-5" /> {t("api-keys")}
									</h2>
									<p className="mb-4 text-sm text-muted-foreground">{t("settings.api-keys")}</p>
									<div className="space-y-4">
										{Object.entries(localApiKeys).map(([key, value]) => (
											<div key={key}>
												<Label htmlFor={`api-${key}`}>{key}</Label>
												<Input
													id={`api-${key}`}
													value={value}
													onChange={(e) => handleApiKeyChange(key, e.target.value)}
													className="mt-1 max-w-md"
													type="password"
												/>
											</div>
										))}
										{Object.keys(localApiKeys).length === 0 && (
											<p className="text-sm text-muted-foreground">No API keys configured.</p>
										)}
									</div>
								</div>
							)}

							{/* Importers */}
							{activeItem === "import-csv"   && <CsvImporter />}
							{activeItem === "import-steam" && <SteamImporter />}
							{activeItem === "import-epic"  && <EpicImporter />}
							{activeItem === "import-gog"   && <GogImporter />}

							{/* Exporters */}
							{activeItem === "export-csv" && (
								<div>
									<h2 className="mb-4 flex items-center gap-2 text-xl font-semibold">
										<FileOutput className="h-5 w-5" /> {t("csv-exporter")}
									</h2>
									<p className="mb-4 text-sm text-muted-foreground">
										{t("exportGamesToCSV") || "Export your entire game library to a CSV file."}
									</p>
									<Button onClick={() => db.exportToCSV()}>
										<FileOutput className="mr-2 h-4 w-4" /> {t("export") || "Export"}
									</Button>
								</div>
							)}
							{activeItem === "export-archive" && (
								<div>
									<h2 className="mb-4 flex items-center gap-2 text-xl font-semibold">
										<Archive className="h-5 w-5" /> {t("archive-exporter")}
									</h2>
									<p className="mb-4 text-sm text-muted-foreground">
										{t("exportGamesToArchive") || "Export your entire game library (including media) to a ZIP archive."}
									</p>
									<Button onClick={() => db.exportToArchive()}>
										<Archive className="mr-2 h-4 w-4" /> {t("export") || "Export"}
									</Button>
								</div>
							)}

							{/* About */}
							{activeItem === "about" && (
								<div className="flex flex-col items-center text-center">
									<img src={logoSvg} alt="Meteoric" className="mb-4 h-40 w-40" />
									<h2 className="text-2xl font-bold">Meteoric</h2>
									<p className="mt-1 rounded-full bg-primary/10 px-4 py-1 text-sm text-primary">
										v{appVersion}
									</p>
									<div className="mt-6 flex gap-4">
										<a href="https://github.com/Nytuo/Meteoric" target="_blank" rel="noreferrer" className="text-sm text-muted-foreground hover:text-foreground">GitHub</a>
										<a href="https://github.com/Nytuo/Meteoric/wiki" target="_blank" rel="noreferrer" className="text-sm text-muted-foreground hover:text-foreground">{t("documentation")}</a>
										<a href="https://github.com/Nytuo/Meteoric/issues" target="_blank" rel="noreferrer" className="text-sm text-muted-foreground hover:text-foreground">{t("reportIssue")}</a>
									</div>
									<div className="mt-6 flex gap-3">
										<Button variant="outline" onClick={openProgramFolder}>
											<FolderOpen className="mr-2 h-4 w-4" /> {t("open-program-folder")}
										</Button>
										<Button variant="outline" onClick={openDataFolder}>
											<FolderOpen className="mr-2 h-4 w-4" /> {t("open-data-folder")}
										</Button>
									</div>
								</div>
							)}
						</div>
					</ScrollArea>
				</div>
			</DialogContent>
		</Dialog>
	);
}
